on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'master' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install
      - name: Build artifacts
        run: yarn build
      - name: Zip project
        run: |
          zip -r -j dist.zip dist/
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          curl --fail --silent --location --output ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar -zxf ghr.tar.gz
          ./ghr_v0.13.0_linux_amd64/ghr -replace -delete -n Latest -c $GITHUB_SHA latest dist.zip
